### PR TITLE
Skip tests requiring NUMA if NUMA is not supported

### LINKED ISSUE #635: Cannot run ctest on WSL2 due to the lack of NUMA
## Environment Information

- UMF version (hash commit or a tag):                         2c608df489bc818dacd35b8ed9951b8f8ea615ae
- OS(es) version(s):                                          (WSL2) Ubuntu 22.04.4
- kernel version(s):                                          (WSL2, Linux kernel) 5.15.153.1-microsoft-standard-WSL2
- compiler, libraries, and other related tools version(s):    libnuma-dev (2.0.14-3ubuntu2)

### Additional environment information
- WSL2
- no NUMA support

## Reproduction of the bug:

When the unmodified project is built, enter the build directory and execute:

```bash
$ ctest --output-on-failure
```

## How often bug is revealed:

Always

## Actual behavior:

Failing tests:
```
8 - umf-provider_os_memory_multiple_numa_nodes (Subprocess aborted)
9 - umf-memspace_numa (Failed)
11 - umf-memspace_host_all (Failed)
12 - umf-memspace_highest_capacity (Failed)
13 - umf-memspace_highest_bandwidth (SEGFAULT)
14 - umf-memspace_lowest_latency (SEGFAULT)
```

Tests output log include information:
```Failed to initialize libnuma```

```numa_available()``` in ```provider_os_memory_multiple_numa_nodes.cpp``` returns -1

## Expected behavior:

All tests pass

## Details

Additionally, with ```numactl``` installed on the system, running ```numactl --show``` in the terminal shows:
```No NUMA support available on this system.```

## Additional information about Priority and Help Requested:

Are you willing to submit a pull request with a proposed change? Yes

Requested priority:                         Low

### PR DESCRIPTION
**Pull request by EuphoricThinking**
### Description

Checks with numa_available() whether NUMA is supported on the system, then runs tests requiring NUMA according to the result. 

- Adds GTEST_SKIP() or substitutes GTEST_FAIL() with GTEST_SKIP() if failure has been determined by the lack of NUMA support;
- removes UT_ASSERTs checking for NUMA if NUMA support has been checked in the test fixture;
- allows uninstantiated tests in /test/provider_os_memory_multiple_numa_nodes.cpp, which suppresses failures caused by GoogleTestVerification test suite - the potentially uninstantiated tests are never run but skipped by the fixture if NUMA is not supported
- a helper function get_available_numa_nodes() in /test/provider_os_memory_multiple_numa_nodes.cpp returns an empty vector in case of lacking NUMA support (which causes tests to be uninstantiated)
- in examples/memspace, in case of NUMA not supported, the exit code is 0, however, the error message can be displayed with `ctest --verbose` instead of `ctest --output-on-failure`

Fixes #635 

Yours first customer ❤️ 
### Checklist

- [x] Code compiles without errors locally
- [x] All tests pass locally
- [ ] CI workflows execute properly

- [ ] CI workflows, not executed per PR (e.g. Nightly), execute properly 
- [ ] New tests added, especially if they will fail without my changes
- [ ] Added/extended example(s) to cover this functionality
- [ ] Extended the README/documentation
- [ ] All newly added source files have a license
- [ ] All newly added source files are referenced in CMake files
- [ ] Logger (with debug/info/... messages) is used

### CODE REVIEW

**Review by lplewa — CHANGES_REQUESTED** [review]

File: test/memspaces/memspace_fixtures.hpp [hunk 1]
```diff
@@ -29,7 +29,7 @@ struct numaNodesTest : ::umf_test::test {
         ::umf_test::test::SetUp();
 
         if (numa_available() == -1 || numa_all_nodes_ptr == nullptr) {
```
Comment (PatKamin) [inline test/memspaces/memspace_fixtures.hpp:31]: Please, create a common function for this check in this struct and call it in inheriting structs.

Comment (lplewa) [reply test/memspaces/memspace_fixtures.hpp:31]: What do you want exactly?

Something like this will not work: 
``` c
void checknuma(){
    if (numa_available() == -1 || numa_all_nodes_ptr == nullptr) {
        GTEST_SKIP() << "XXX"
    }
}

```
Unless you will use it in this way:
``` c
  checknuma()
  if (IsSkipped()) return;
```
What is probably pointless

Comment (PatKamin) [reply test/memspaces/memspace_fixtures.hpp:31]: OK, leave it then.

File: .gitignore [hunk 2]
```diff
@@ -79,6 +80,7 @@ out/
 
 # Temporary files
 *.~vsdx
+..gitignore.swp
```
Comment (lplewa) [inline .gitignore:83]: ??

File: examples/common/utils_examples.h [hunk 3]
```diff
@@ -0,0 +1,6 @@
+#ifndef UTILS_EXAMPLES_H
```
Comment (lplewa) [inline examples/common/utils_examples.h:1]: add licence

File: examples/common/utils_examples.h [hunk 4]
```diff
@@ -0,0 +1,6 @@
...
+#define UTILS_EXAMPLES_H
+
+#define test_skip_error_code 125
+
+#endif /* UTILS_EXAMPLES_H */
```
Comment (lplewa) [inline examples/common/utils_examples.h:6]: add new line at the end of the file.

File: examples/memspace/memspace_hmat.c [hunk 5]
```diff
@@ -63,7 +63,7 @@ int main(void) {
     // Check if NUMA is available
     if (numa_available() < 0) {
         fprintf(stderr, "NUMA is not available on this system.\n");
-        return -1;
+        return 0;
```
[the remark this answers is not in the document]
Comment (EuphoricThinking) [reply examples/memspace/memspace_hmat.c]: Done; added a define with `test_skip_error_code` in `examples/common/utils_examples.h`

File: .gitignore [hunk 6]
```diff
@@ -63,6 +63,7 @@ docs/
 # Build files
 /build*/
 out/
+/test/build/
```
[the remark this answers is not in the document]
Comment (EuphoricThinking) [reply .gitignore:66]: I have removed that part

File: .gitignore (hunk 2 above)
Comment (EuphoricThinking) [reply .gitignore]: I am going to create a new PR with this line changed to `*.swp`

File: examples/CMakeLists.txt [hunk 7]
```diff
@@ -167,6 +167,8 @@ else()
 endif()
 
 if(LINUX)
+    set(SKIP_CODE 125)
```
[the remark this answers is not in the document]
Comment (EuphoricThinking) [reply examples/CMakeLists.txt]: Done

File: examples/common/utils_examples.h (hunk 3 above)
Comment (EuphoricThinking) [reply examples/common/utils_examples.h:10]: Done

File: examples/common/utils_examples.h (hunk 4 above)
Comment (EuphoricThinking) [reply examples/common/utils_examples.h]: Done

**Review by ldorau — CHANGES_REQUESTED** [review]
Regarding your commit message:
image

Please adjust it to common commit message guidelines, for example:
- https://www.gitkraken.com/learn/git/best-practices/git-commit-message#git-commit-message-structure
- https://www.conventionalcommits.org/en/v1.0.0/#summary
- https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

It could be for example:

```
Skip tests and examples requiring NUMA if NUMA is not supported

Skip tests and examples requiring NUMA enabled in CMakeLists.txt.
The error code for skipping tests is included in helper header files
for examples/ and tests/.

Signed-off-by: ...
```

File: examples/common/utils_examples.h [hunk 8]
```diff
@@ -0,0 +1,16 @@
...
+ * Under the Apache License v2.0 with LLVM Exceptions. See LICENSE.TXT.
+ * SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+ *
+ */
+
+#ifndef UTILS_EXAMPLES_H
+#define UTILS_EXAMPLES_H
+
+// Needed for CI
+#define test_skip_error_code 125
```
Comment (ldorau) [inline examples/common/utils_examples.h:14]: Defines are usually in CAPITAL letters. Could you replace it?

**Review by ldorau — CHANGES_REQUESTED** [review]

File: examples/common/utils_examples.h (hunk 8 above)
Comment (EuphoricThinking) [reply examples/common/utils_examples.h]: Done

**Review by ldorau — APPROVED** [review]

**Review by lplewa — APPROVED** [review]

**Review by lukaszstolarczuk — COMMENTED** [review]
FYI, your commit is veeery descriptive - it's not required to describe, line be line, what you did in the change (we can see that in the commit itself), it's rather useful to describe it high level and provide a reason why. In here it's ok, because you're fixing an issue, so all the details should be there :)

File: test/memspaces/memspace_fixtures.hpp [hunk 9]
```diff
@@ -30,7 +30,7 @@ struct numaNodesTest : ::umf_test::test {
...
-            GTEST_FAIL() << "Failed to initialize libnuma";
+            GTEST_SKIP() << "Failed to initialize libnuma; skipped";
```
[the remark this answers is not in the document]
Comment (EuphoricThinking) [reply test/memspaces/memspace_fixtures.hpp]: Done

File: examples/common/utils_examples.h [hunk 10]
```diff
@@ -0,0 +1,16 @@
+/*
+ *
+ * Copyright (C) 2024 Intel Corporation
+ *
+ * Under the Apache License v2.0 with LLVM Exceptions. See LICENSE.TXT.
+ * SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
+ *
+ */
+
+#ifndef UTILS_EXAMPLES_H
```
[the remark this answers is not in the document]
Comment (EuphoricThinking) [reply examples/common/utils_examples.h]: Done

**Review by lukaszstolarczuk — APPROVED** [review]
